version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - run: npm ci
      - run: |
          npm run lint:eslint
          npm run lint:prettier
      - run: npm run build
      - run: npm run test
